version: '3.8'

networks:
  helpdesk-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - helpdesk-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/helpdesk
      - JWT_SECRET=your-secret-key
      - STUB_MODE=true
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - helpdesk-network
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - helpdesk-network
    restart: unless-stopped

volumes:
  mongodb_data: